---
- hosts: webserver
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u dharmendrgowda2107@gmail.com -p Gowda@2107 gowdaa.jfrog.io   
    
    - name: pull an image
      shell: docker pull gowdaa.jfrog.io/docker-docker/dharma:v{{BUILD_NUMBER}}

   # - name: remove container
    #  shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 gowdaa.jfrog.io/docker-docker/dharma:v{{ BUILD_NUMBER }}
 
   
